version: "3.7"

services:
  web_a:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VSN: 0.1.0
        APP_NAME: football_scores
    ports:
      - 4000
    env_file:
      - ./docker/.env
    depends_on:
      - db
  web_b:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VSN: 0.1.0
        APP_NAME: football_scores
    ports:
      - 4000
    env_file:
      - ./docker/.env
    depends_on:
      - db
  web_c:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VSN: 0.1.0
        APP_NAME: football_scores
    ports:
      - 4000
    env_file:
      - ./docker/.env
    depends_on:
      - db
  db:
    image: postgres:11.3
    env_file:
      - ./docker/.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  proxy:
    image: haproxy:2.0.4-alpine
    volumes:
      - ./docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - web_a
      - web_b
      - web_c
    ports:
      - 4000:80

volumes:
  postgres:
